### ISSUE TITLE
Why did you return -EPERM?

### ISSUE THREAD

**Issue by frankQAQ-wang** [awslabs/damo#25]
hello amd world are the other two ctxs that don't use,  there don't have kdamond obviously! If you want to free it, you need to create it and keep it. 

//dmesg
Aug 24 09:11:51 debian kernel: damon: kdamond (11274) starts
Aug 24 09:11:51 debian kernel: damon: kdamond (11275) starts
Aug 24 09:11:51 debian kernel: damon: kdamond (11275) finishes
Aug 24 09:11:51 debian kernel: damon: kdamond (11276) starts
Aug 24 09:11:51 debian kernel: damon: kdamond (11276) finishes

//user
root@debian:~/user-damon/damo# strace -o strace.txt -f -s 128 ./damo record 10370
# damon attrs: 5000 100000 1000000 10 1000  1048576 /root/user-damon/damo/damon.data
Press Ctrl+C to stop
^C
signal 2 received
/bin/bash: line 1: echo: write error: Operation not permitted
failed to turn damon off!
root@debian:~/user-damon/damo#

//debugfs
root@debian:/sys/kernel/debug/damon# ls
attrs          hello         kdamond_pid  monitor_on  rm_contexts  target_ids  world
direct_scheme  init_regions  mk_contexts  record      schemes      version

//kernel
```
int damon_start(struct damon_ctx **ctxs, int nr_ctxs)
{
        int i;
        int err = 0;

        mutex_lock(&damon_lock);
        if (nr_running_ctxs) {
                mutex_unlock(&damon_lock);
                return -EBUSY;
        }

        for (i = 0; i < nr_ctxs; i++) {
                err = __damon_start(ctxs[i]);
                if (err)
                        break;
                nr_running_ctxs++;
        }
        mutex_unlock(&damon_lock);

        return err;
}
```

**Comment by sj-aws** [comment]
Cannot fully understand the first sentence, but seems you somehow got '-EPERM' from 'damo'.

In short, the error value can be returned on some specific timing, but it doesn't means your system has some problem.

DAMON returns the error code if you tried to stop monitoring while no monitoring thread is running.  The monitoring thread can be stopped when user explicitly asked, or when the monitoring target became invalid (e.g., in case of the virtual address space monitoring, when the process of the virtual address space is terminated).  In this case, seems monitoring target became invalid and therefore the monitoring thread was about to self-stopped.  Almost at the same time, 'damo' has asked to stop the monitoring thread, and therefore it tried to stop the monitoring thread.  However, at this time, the self-stop has done, and therefore 'damo' was end up trying to stop the monitoring thread while there is no more monitoring thread.  Anyway, because the monitoring thread is safely stopped, there could be no problem.
