### ISSUE TITLE
A question about the meaning of heatmap values

### ISSUE THREAD

**Issue by honggyukim** [awslabs/damo#45]
Hi SeongJae,

I've recorded a target program to investigate the memory access patterns of https://github.com/facebookresearch/dlrm.

I've got a heatmap and it looks most of the memory regions are cold and linearly accessed as follows.

I'm just wondering what's the meaning of the heatness values at the right hand side of the heatmap.
![access_pattern_heatmap](https://github.com/awslabs/damo/assets/19642328/b40c4d07-a328-4f26-8138-6cd14c2922a7)

I found that the value is calculated at [1] and printed at [2], but it doesn't look straight forward to me.

Could you please explain about it? Thanks!

[1] https://github.com/awslabs/damo/blob/v1.8.2/damo_heats.py#L50-L55
[2] https://github.com/awslabs/damo/blob/v1.8.2/damo_heats.py#L171

**Comment by sj-aws** [comment]
Hi Honggyu,


Thank you for sharing this great results with us!  In short, the value is relative access frequency of the given memory region at the given time, which is in range of `[0, aggregation interval (--aggr) / sampling interval (--sample)]`.  Because `--aggr` is 100ms and `--sample` is 5ms by default, the value should be in the range of `[0, 20]` if you didn't set the values on your own.

In more detail, DAMON conceptually scans accesses to monitoring target address space every "sampling interval".  As a result, DAMON can know which memory region has accessed since the last scanning.  If it shows a region has accessed since the last scanning, it increments an internal counter for the region.  For every "aggregation interval", DAMON reports the acuumulated internal counter to users.  The value is called `nr_accesses`.  More precise name would be "number of sampling intervals within last aggregation interval that DAMON has shown access to the region".

`damo-report-heats` needs to convert the results into a heatmap foramt.  Heatmap format should represent the results with pixels having same time/address lengths.  In contrast, the DAMON allows the monitoring results region to have various size.  For the reason, `damo-report-heats` convert the results to the pixels.  The code you mentioned is for the purpose.

Please feel free to ask more questions or clarifications.

**Comment by honggyukim** [comment]
Hi SeongJae,

Sorry for the late response. I'm not working on damon full time so couldn't take time to digest your full and detail explanation.

> Thank you for sharing this great results with us!

Pleasure to hear that!

> In short, the value is relative access frequency of the given memory region at the given time, which is in range of [0, aggregation interval (--aggr) / sampling interval (--sample)]. Because --aggr is 100ms and --sample is 5ms by default, the value should be in the range of [0, 20] if you didn't set the values on your own.

I found that the value is in the range [0, 20] as you mentioned. Thanks.

> In more detail, DAMON conceptually scans accesses to monitoring target address space every "sampling interval". As a result, DAMON can know which memory region has accessed since the last scanning, it increments an internal counter for the region. For every "aggregation interval", DAMON reports the acuumulated internal counter to users. The value is called nr_accesses. More precise name would be "number of sampling intervals within last aggregation interval that DAMON has shown access to the region".

I understood that damon periodically checks active bit in pte every sampling interval and increment a counter value whether the accessed is found during the 5ms. Then print the collected counter value after the aggregation interval, 100ms, is passed. That's why the value is within the range [0, 20].

> damo-report-heats needs to convert the results into a heatmap foramt. Heatmap format should represent the results with pixels having same time/address lengths. In contrast, the DAMON allows the monitoring results region to have various size. For the reason, damo-report-heats convert the results to the pixels. The code you mentioned is for the purpose.

Ah. this is the reason why the values become float point numbers rather than accumulated integer counter values range in [0, 20].

> Please feel free to ask more questions or clarifications.

Thanks very much for your explanation again, but it would be much better if there is some comments in the source code. I still think that the meaning of each variable isn't clear to me. For example, what are `duration`, `fraction_{end,start}` and etc.
```py
            heat = region.nr_accesses.samples * duration * (
                    fraction_end - fraction_start)

            pixel = pixels[addr_idx]
            heat += pixel.heat * pixel_sz
            pixel.heat = float(heat) / pixel_sz
```

**Comment by sj-aws** [comment]
> Sorry for the late response.

No problem at all.  Please take your time and work on your pace.  I'm happy to help you on your pace.

> it would be much better if there is some comments in the source code.

I agree.  The code needs some cleanups.  I will try to make it better to read.  Nevertheless, please feel free to send patches if you have any idea always :)

**Comment by honggyukim** [comment]
And I will join the call later today. See you soon :)

**Comment by sj-aws** [comment]
Cool, looking forward!

**Comment by sj-aws** [comment]
Hi Honggyu, I made some comments cleanup with abovely mentioned commit.  Do you think it suffices to answer your question?  Or, do you still have some ideas to improve it?

**Comment by honggyukim** [comment]
It looks clear and good now. Thanks for your help!
