### ISSUE TITLE
Avoid `commit` in damo show and status

### ISSUE THREAD

**Issue by honggyukim** [awslabs/damo#68]
Hi SeongJae,

It looks `damo show` and `damo status` both write `commit` to `status`. But it makes conflict when running `damo show` and `damo status` together.

I feel it's quite useful to run those commands using `watch` command to run them repeatedly every second as follows.
```
# In terminal 1
$ watch -n 1 ./damo show

# In terminal 2
$ watch -n 1 ./damo status
```
I think it's not require to write `commit` to `status` for those commands because they don't change damon status so I'm wondering if there is a way to skip the `commit`. If not, then it'd be useful to have an option to avoid the `commit`.

Thanks.

**Comment by honggyukim** [comment]
What I mean by conflicts is that I sometimes see a failure as follows when running `damo show` and `damo status` with `watch` command.
```
$ ./damo status
writing update_schemes_stats to /sys/kernel/mm/damon/admin/kdamonds/0/state failed ([Errno 16] Device or resource busy)
```

**Comment by sj-aws** [comment]
Hi Honggyu,

Thank you for this kind report.

`status` and `show` need to write commands to `state` file of the kdamond for asking the kdamond to update the status/regions information so that `damo` can retrieve fresh data.  The writings could result in such `-EBUSY` error if made while the other write is still ongoing.  The commands include `commit` as you also mentioned, though it is not the only single command they could write to the file.

Anyway, I think your usage is somewhat that many people could commonly do, and agree that the error is better to not shown.  I think we could make `show` and `status` to simply handle the failure by wait a little bit and retry.  I will try to implement that soon.

Also, Today I learned `watch` command, courtesy of this doc.  I used to do `while :; do ... ; sleep 1; done` manually before.  Thank you!

**Comment by honggyukim** [comment]
Hi SeongJae,

> status and show need to write commands to state file of the kdamond for asking the kdamond to update the status/regions information so that damo can retrieve fresh data.

Ah. it looks like we can run `damo status` and `damo show` without emitting `commit` to `state`, but it would show stale data.

> The commands include commit as you also mentioned, though it is not the only single command they could write to the file.

If so, there could be more chance to get `-EBUSY` as you mentioned.

> I think we could make show and status to simply handle the failure by wait a little bit and retry. I will try to implement that soon.

It'd be really helpful if this is implemented. Thanks!

> Also, Today I learned `watch` command, courtesy of this doc. I used to do `while :; do ... ; sleep 1; done` manually before.

I'm glad to hear that you like it :)

**Comment by sj-aws** [comment]
Implemented the suggested retries with simple backoff algorithm via commit e80474d.  Please feel free to open this again if it doesn't solve your issue.

**Comment by sj-aws** [comment]
Please note that there is a maximum number of retries (5).  Hence, you may still be able to occasionally show the conflict.  If it turns out the default number (5) is too small, we could increase it.  We could also consider adding an option for setting the maximum number if needed.

**Comment by honggyukim** [comment]
> Please note that there is a maximum number of retries (5). Hence, you may still be able to occasionally show the conflict. If it turns out the default number (5) is too small, we could increase it. We could also consider adding an option for setting the maximum number if needed.

Thanks for the explanation. I will see if I see another failure due to the retry limit. I'm fine with the current change for now.
